### ISSUE TITLE
Android release build fail - index.js: Cannot find module '../../dist/mappings.json'

### ISSUE THREAD

**Issue by joaom182** [callstack/react-native-paper#1097]
## Environment

Paper - 2.14.0
React-native - 0.58.5

## Description

On Android prod build returns the following error

```
> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.

index.js: Cannot find module '../../dist/mappings.json'

Error: Cannot find module '../../dist/mappings.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vsts/agent/2.150.3/work/1/s/node_modules/react-native-paper/src/babel/index.js:1:80)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)


> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
```

**Comment by joaom182** [comment]
For some reason on `npm install` or `yarn` process, is not executing script **prepare** (`node ./scripts/generate-mappings`) contained on package.json

**Comment by ferrannp** [comment]
@joaom182 haven't seen this before, can you update react-native and react-native-paper to latest and provide a repro if this still happens?

**Comment by jaysbytes** [comment]
inactive, closing
