### ISSUE TITLE
Requested keys of a value that is not an object.

### ISSUE THREAD

**Issue by joaom182** [callstack/react-native-paper#1163]
## Environment

react-native-paper 2.14.0
react-native 0.58.5

## Description

This errors only occurs on Android 9 when the `withTheme` method is called to enhance any component.

```error
TypeError: TypeError: Requested keys of a value that is not an object.

This error is located at:
    in withTheme(n)
    in Connect(withTheme(n))
    in RCTView
    in h
    in n
    in p
    in withTheme(n)
    in Connect(withTheme(n))
    in p
    in RCTView
    in Portal.Host
    in n
    in s
    in Unknown
    in Unknown
    in v
    in RCTView
    in RCTView
    in c
  at [native code] keys(:0:0)
  at mergeObject(node_modules/deepmerge/dist/umd.js:56:16)
  at deepmerge(node_modules/deepmerge/dist/umd.js:83:17)
  at ComponentWithMethods(node_modules/@callstack/react-theme-provider/lib/createWithTheme.js:64:49)
  at updateExpirationTime(node_modules/@callstack/react-theme-provider/lib/createWithTheme.js:139:12)
  at beginWork(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:4394:33)
  at performUnitOfWork(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5321:14)
  at renderRoot(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5362:28)
  at performWorkOnRoot(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5960:11)
  at performWork(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5900:7)
  at requestWork(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5802:11)
  at scheduleWork(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:5703:7)
  at updateContainer(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6347:3)
  at render(node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-prod.js:6516:7)
  at renderApplication(node_modules/react-native/Libraries/ReactNative/renderApplication.js:59:28)
  at run(node_modules/react-native/Libraries/ReactNative/AppRegistry.js:100:9)
  at _eventLoopStartTime(node_modules/react-native/Libraries/ReactNative/AppRegistry.js:195:23)
  at this(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:373:10)
  at DebuggerInternal(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:5)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:329:14)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:109:17)
```

**Comment by jaysbytes** [comment]
Closing for inactivity
