### ISSUE TITLE
Error: Unable to resolve module `./components/Checkbox` from `node_modules/react-native-paper/lib/module/index.js`:

### ISSUE THREAD

**Issue by jchandr** [callstack/react-native-paper#1882]
## Environment
`
"dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "axios": "^0.19.2",
    "qrcode": "^1.4.4",
    "react": "16.9.0",
    "react-native": "^0.62.2",
    "react-native-bluetooth-escpos-printer": "0.0.5",
    "react-native-camera": "^3.23.1",
    "react-native-canvas": "^0.1.37",
    "react-native-config": "^1.0.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-paper": "^3.9.0",
    "react-native-permissions": "^2.1.2",
    "react-native-qrcode-scanner": "^1.4.0",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.3.0",
    "react-native-svg": "^12.0.3",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-logger": "^3.0.6",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",
    "rn-secure-storage": "^2.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^25.5.1",
    "eslint": "^6.5.1",
    "jest": "^25.5.3",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
`
## Description

**## Reproducible Demo**

`
error: Error: Unable to resolve module `./components/Checkbox` from `node_modules/react-native-paper/lib/module/index.js`:

None of these files exist:
  * node_modules/react-native-paper/lib/module/components/Checkbox(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-native-paper/lib/module/components/Checkbox/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jchan/Documents/soryasteelsProject/soryasteelsSalesmanAppReactNative/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
`

**Comment by jchandr** [comment]
resetting the transform cache and fresh npm install worked. 

```
npx react-native start --reset-cache
npm install
```
