### ISSUE TITLE
react-native:  /worker/import-export-plugin'

### ISSUE THREAD

**Issue by sabrine2433** [callstack/react-native-paper#2265]
When trying to run the React Native web browser It shows a red screen error message:

Failed to construct transformer:  Error: Cannot find module './worker/import-export-plugin'

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Pc\Desktop\reactNative\tout\test\node_modules\metro-config\node_modules\metro\src\JSTransformer\worker.js:123:28)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',

**Comment by RichardLindhout** [comment]
Are you using Expo?

**Comment by sabrine2433** [comment]
@RichardLindhout yes

**Comment by RichardLindhout** [comment]
Does this problem occur when creating a fresh project or when does this happen. Can you make a reproduction using snack.expo.io?
