### ISSUE TITLE
Dark Mode Fails When Merging React Native Paper and React Navigation Themes

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-paper#2739]
### Current behaviour

When switching to "dark" mode in react native web I get the error: invalid pattern #1E1E1E and #232323.  This issue is coming from the "surface" component in the "card" component.

Note that "light" mode works fine.

### Expected behaviour

It should switch to dark mode without issue.

### Code sample
```
import { DefaultTheme as NavDefaultTheme, DarkTheme as NavDarkTheme } from '@react-navigation/native';
import { DefaultTheme as PaperDefaultTheme, DarkTheme as PaperDarkTheme } from 'react-native-paper';

// console.log(PaperDarkTheme)
// console.log(NavDarkTheme)

export default {
  light: {
    ...PaperDefaultTheme,
    ...NavDefaultTheme,
    colors: {
      ...PaperDefaultTheme.colors,
      ...NavDefaultTheme.colors,
      form: '#fff',
      readonly: '#ccc',
      textMuted: "rgba(0, 0, 0, 0.54)",
      textDark: "#000",
      shadowColor: 'rgb(39, 39, 41)',
      primary: "#039"
    },
  },
  dark: {
    ...PaperDarkTheme,
    ...NavDefaultTheme,
    colors: {
      ...PaperDarkTheme.colors,
      ...NavDarkTheme.colors,
      form: '#ccc',
      readonly: 'rgb(39, 39, 41)',
      textMuted: "rgba(229, 229, 231, 0.6)",
      textDark: "#000",
      card: 'rgb(39, 39, 39)',
      primary: "#91a9d0",
      shadowColor: '#000'
    },
  },
};
```

### Screenshot

![image](https://user-images.githubusercontent.com/3186418/118817433-338b6f00-b881-11eb-88ed-484c3513729d.png)

### Console log

`Uncaught Invariant Violation: invalid pattern #1E1E1E and #232323
    at invariant (http://localhost:19006/static/js/bundle.js:25871:15)
    at checkPattern (http://localhost:19006/static/js/bundle.js:204250:62)
    at createInterpolationFromStringOutputRange (http://localhost:19006/static/js/bundle.js:204213:3)
    at createInterpolation (http://localhost:19006/static/js/bundle.js:204107:12)
    at new AnimatedInterpolation (http://localhost:19006/static/js/bundle.js:204288:28)
    at AnimatedValue.interpolate (http://localhost:19006/static/js/bundle.js:205730:12)
    at overlay (http://localhost:19006/static/js/bundle.js:176262:22)
    at Surface (http://localhost:19006/static/js/bundle.js:171994:124)
    at renderWithHooks (http://localhost:19006/static/js/bundle.js:152405:18)
    at mountIndeterminateComponent (http://localhost:19006/static/js/bundle.js:155084:13)
    at beginWork (http://localhost:19006/static/js/bundle.js:156198:16)
    at HTMLUnknownElement.callCallback (http://localhost:19006/static/js/bundle.js:137790:14)
    at Object.invokeGuardedCallbackDev (http://localhost:19006/static/js/bundle.js:137839:16)
    at invokeGuardedCallback (http://localhost:19006/static/js/bundle.js:137894:31)
    at beginWork$1 (http://localhost:19006/static/js/bundle.js:160805:7)
    at performUnitOfWork (http://localhost:19006/static/js/bundle.js:159759:12)
    at workLoopSync (http://localhost:19006/static/js/bundle.js:159732:22)
    at performSyncWorkOnRoot (http://localhost:19006/static/js/bundle.js:159358:9)
    at http://localhost:19006/static/js/bundle.js:148691:24
    at unstable_runWithPriority (http://localhost:19006/static/js/bundle.js:219522:12)
    at runWithPriority$1 (http://localhost:19006/static/js/bundle.js:148641:10)
    at flushSyncCallbackQueueImpl (http://localhost:19006/static/js/bundle.js:148686:7)
    at flushSyncCallbackQueue (http://localhost:19006/static/js/bundle.js:148674:3)
    at scheduleUpdateOnFiber (http://localhost:19006/static/js/bundle.js:158801:9)
    at dispatchAction (http://localhost:19006/static/js/bundle.js:153262:5)
    at http://localhost:19006/static/js/bundle.js:55568:17
10index.js:1 The above error occurred in the <Surface> component:
    in Surface (created by Context.Consumer)
    in ThemedComponent (created by withTheme(Surface))
    in withTheme(Surface) (created by Card)
    in Card (created by Context.Consumer)
    in ThemedComponent (created by withTheme(Card))
    in withTheme(Card) (created by PostCard)
    in div (created by View)
    in View (created by PostCard)
    in PostCard`

### What have you tried

I've overwritten the 'dark = true'  property as a temporarily fix, but am losing some of the proper dark theme formatting as a result.

```
dark: {
    ...PaperDarkTheme,
    ...NavDarkTheme,
    dark: false, // OVERRIDE DUE TO BUG IN REACT NATIVE PAPER
    colors: {
      ...PaperDarkTheme.colors,
      ...NavDarkTheme.colors,
      form: '#ccc',
      readonly: 'rgb(39, 39, 41)',
      textMuted: "rgba(229, 229, 231, 0.6)",
      textDark: "#000",
      card: 'rgb(39, 39, 39)',
      primary: "#91a9d0",
      shadowColor: '#000'
    },
  },
```

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | expo web
| react-native          | 16.13.1
| react-native-paper    | 4.8.1
| node                  | 14.6.1
| npm or yarn           | yarn
| expo sdk              | 41
| react  navigation native              | 5.9.4

**Comment by buffaloDeveloper** [comment]
Something is going wrong with the theme property: dark: true

**Comment by buffaloDeveloper** [comment]
Still an issue...
