### ISSUE TITLE
Cannot find module '...node_modules/react-native-paper/package.json'

### ISSUE THREAD

**Issue by defrian** [callstack/react-native-paper#293]
### Current behaviour

When I execute react-native link I receive the following error:
`Cannot find module '...node_modules/react-native-paper/package.json'`

### Expected behaviour

No Error

### Code sample

n/a

### Screenshots (if applicable)

```
Scanning folders for symlinks in /Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules (19ms)
{ Error: Cannot find module '/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native-paper/package.json'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)    at require (internal/module.js:11:18)
    at getRNPMConfig (/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native/local-cli/core/index.js:55:3)    at Object.getDependencyConfig (/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native/local-cli/core/index.js:117:18)
    at deps.reduce (/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native/local-cli/link/getDependencyConfig.js:9:24)
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native/local-cli/link/getDependencyConfig.js:6:1
5)
    at Object.link (/Users/andrefritsch/Entwicklung/React-Native/WhatsForDinner/node_modules/react-native/local-cli/link/link.js:133:24) code: 'MODULE_NOT_FOUND' }
```

### What have you tried

delete ios and android folder.
run `react-native eject`
run `react-native link`

### Your Environment

| software              | version
| ----------------  | -------
| ios                        | 11
| react-native          | 0.53.3
| react-native-paper    |^1.0.1
| node                  |9.6.1
| npm or yarn           |npm

**Comment by ferrannp** [comment]
Can you provide code or a repo link for this?

**Comment by robbiemu** [comment]
I get this error running the example direct from GitHub.

steps to reproduce:

1. `git clone https://github.com/callstack/react-native-paper expo`
2. `cp expo/example expo-demo`, `cd expo-demo`
3. `yarn install` // errored out and requested I upgrade yarn so  .. I did that but then:
4. `yarn upgrade` `npm install` `nom audit` // success, and 0 vulnerabilities
5. `yarn install` // get the lock file back
6. `yarn start`

this starts Metro bundler but it reports:

```
node:80514) UnhandledPromiseRejectionWarning: Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/robertotomas/Public/Harvard/Thesis/demos/expo-paper-demo/metro.config.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Module._compile (/Users/robertotomas/Public/Harvard/Thesis/demos/expo-paper-demo/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Object.newLoader [as .js] (/Users/robertotomas/Public/Harvard/Thesis/demos/expo-paper-demo/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:620:32)
ERROR
15:30
(node:80514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:80514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
