### ISSUE TITLE
Open handles when testing with jest

### ISSUE THREAD

**Issue by atheck** [callstack/react-native-paper#3338]
Hi, when I run component tests with jest there are open handles which keep jest from exiting. Running jest with `--detectOpenHandles` I get the following output:

```
> 5 | import { Provider } from "react-native-paper";
    | ^

at ../node_modules/react-native/node_modules/scheduler/cjs/scheduler.development.js:178:17
      at Object.<anonymous> (../node_modules/react-native/node_modules/scheduler/cjs/scheduler.development.js:13:3)
      at Object.<anonymous> (../node_modules/react-native/node_modules/scheduler/index.js:6:20)
      at ../node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:23:17
      at Object.<anonymous> (../node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:17:3)
      at Object.<anonymous> (../node_modules/react-native/Libraries/Renderer/shims/ReactNative.js:21:17)
      at Object.<anonymous> (../node_modules/react-native/Libraries/Animated/AnimatedEvent.js:16:21)
      at Object.<anonymous> (../node_modules/react-native/Libraries/Animated/AnimatedMock.js:13:44)
      at Object.<anonymous> (../node_modules/react-native/Libraries/Animated/Animated.js:19:22)
      at Object.Animated (../node_modules/react-native/index.js:260:12)
      at Object.<anonymous> (../node_modules/react-native-paper/lib/commonjs/components/BottomNavigation/BottomNavigationRouteScreen.tsx:27:16)
      at Object.<anonymous> (../node_modules/react-native-paper/lib/commonjs/components/BottomNavigation/BottomNavigation.tsx:26:1)
      at Object.<anonymous> (../node_modules/react-native-paper/lib/commonjs/index.tsx:25:1)
```
* react-native-paper: 4.12.4
* react-native-vector-icons: 9.2.0
* react-native: 0.68.3

I'm using the "react-native" jest preset. I think there is nothing special in my jest setup.

Can someone help me with that?

**Comment by thymikee** [comment]
Have you mocked the Animated helper? Ex: https://github.com/callstack/react-native-testing-library/blob/7dd403b2ea76df40c04b22fda91773b95d4454c7/examples/reactnavigation/jest-setup.js

**Comment by atheck** [comment]
Yes I'm already mocking the `NativeAnimatedHelper`.

Thank you for your reply @thymikee.
