### ISSUE TITLE
Expo web show warning Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation

### ISSUE THREAD

**Issue by threemak** [callstack/react-native-paper#3539]
### Current behaviour
react_devtools_backend.js:4012 Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`. Make sure to run `pod install` first. Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md 
    at http://localhost:19006/static/js/bundle.js:88326:24
    at ThemedComponent (http://localhost:19006/static/js/bundle.js:1894:39)
    at withTheme(undefined)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at Styled (http://localhost:19006/static/js/bundle.js:28573:33)
    at http://localhost:19006/static/js/bundle.js:28497:24
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at SafeAreaView (http://localhost:19006/static/js/bundle.js:113242:25)
    at Styled (http://localhost:19006/static/js/bundle.js:28573:33)
    at http://localhost:19006/static/js/bundle.js:28497:24
    at LoginComponent (http://localhost:19006/static/js/bundle.js:142347:26)
    at StaticContainer (http://localhost:19006/static/js/bundle.js:6532:16)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6105:23)
    at SceneView (http://localhost:19006/static/js/bundle.js:6425:21)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at Background (http://localhost:19006/static/js/bundle.js:10051:20)
    at Screen (http://localhost:19006/static/js/bundle.js:11159:107)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:11103:23)
    at NativeStackView (http://localhost:19006/static/js/bundle.js:11490:20)
    at PreventRemoveProvider (http://localhost:19006/static/js/bundle.js:6335:24)
    at NavigationContent (http://localhost:19006/static/js/bundle.js:7806:21)
    at http://localhost:19006/static/js/bundle.js:7817:26
    at NativeStackNavigator (http://localhost:19006/static/js/bundle.js:11427:17)
    at UnAuthenticationTab
    at http://localhost:19006/static/js/bundle.js:142074:20
    at AppNavigation (http://localhost:19006/static/js/bundle.js:142078:89)
    at EnsureSingleNavigator (http://localhost:19006/static/js/bundle.js:6105:23)
    at BaseNavigationContainer (http://localhost:19006/static/js/bundle.js:5775:27)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:12275:20)
    at NavigationContainerInner (http://localhost:19006/static/js/bundle.js:11747:25)
    at ThemeProvider (http://localhost:19006/static/js/bundle.js:1775:31)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at PortalHost (http://localhost:19006/static/js/bundle.js:85343:81)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at SafeAreaProviderCompat (http://localhost:19006/static/js/bundle.js:91361:23)
    at Provider (http://localhost:19006/static/js/bundle.js:91248:36)
    at ThemeContextProvider (http://localhost:19006/static/js/bundle.js:142871:23)
    at div
    at http://localhost:19006/static/js/bundle.js:120215:25
    at NativeSafeAreaProvider (http://localhost:19006/static/js/bundle.js:112934:23)
    at SafeAreaProvider (http://localhost:19006/static/js/bundle.js:113106:23)
    at App
overrideMethod @ react_devtools_backend.js:4012
shouldUseNativeDriver @ NativeAnimatedHelper.js:258
TimingAnimation @ TimingAnimation.js:39
start @ AnimatedImplementation.js:142
start @ AnimatedImplementation.js:148
(anonymous) @ TextInput.tsx:310
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
commitRootImpl @ react-dom.development.js:26886
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
(anonymous) @ react-dom.development.js:25607

### Expected behaviour
This message is typically seen when the React Native Animated library is being used with the React Native Paper TextInput component, which does not have native support for animations. In this case, the useNativeDriver prop will have no effect and the animations will be run on the JavaScript thread.

Environment
"dependencies": {
   "@expo/vector-icons": "^13.0.0",
    "@expo/webpack-config": "^0.17.2",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.6",
    "D": "^1.0.0",
    "expo": "~47.0.8",
    "expo-font": "~11.0.1",
    "expo-splash-screen": "~0.17.5",
    "expo-status-bar": "~1.4.2",
    "jest": "^26.6.3",
    "jest-expo": "^47.0.1",
    "nativewind": "^2.0.0-next.65",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-fast-compare": "^3.2.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-paper": "^5.0.1",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-web": "~0.18.9",
    "resize-observer-polyfill": "^1.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@types/react": "~18.0.14",
    "@types/react-native": "~0.70.6",
    "autoprefixer": "^10.4.13",
    "babel-preset-expo": "^9.2.2",
    "cross-env": "^7.0.3",
    "postcss": "^8.4.20",
    "postcss-loader": "^4.2.0",
    "sharp-cli": "^2.1.0",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.6.3"
  },

**Comment by threemak** [comment]
it also show this warning in expo web build

**Comment by threemak** [comment]
And another warning setNativeProps is deprecated. Please update props using React state instead

**Comment by threemak** [comment]
Sorry for that its a issue of react native web its Missing useNativeDriver support.

**Comment by threemak** [comment]
It is a react-native-web issue in the file https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/vendor/react-native/Animated/NativeAnimatedHelper.js
