### ISSUE TITLE
Cannot Run `yarn start` in Docs Folder

### ISSUE THREAD

**Issue by turtlegood** [callstack/react-native-paper#465]
### Current behaviour

Thanks for the wonderful package! I am trying to use the `material-next` branch and want to generate the document. However, after executing the commands as follows, I get an error:

```
git clone ...
git checkout material-next
yarn bootstrap
cd docs
yarn start
```

error:

```
yarn start v0.27.5
$ yarn clean
$ babel-node index
module.js:472
    throw err;
    ^

'rror: Cannot find module 'D:\Swap\react-native-paper\src\components\BottomNavigation
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at D:/Swap/react-native-paper/docs/index.js:34:28
    at Array.map (native)
    at getPages (D:/Swap/react-native-paper/docs/index.js:33:6)
    at serve (D:\Swap\react-native-paper\docs\node_modules\component-docs\src\index.js:133:48)
    at Object.<anonymous> (D:/Swap/react-native-paper/docs/index.js:92:3)
    at Module._compile (module.js:571:32)
    at loader (D:\Swap\react-native-paper\docs\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Swap\react-native-paper\docs\node_modules\babel-register\lib\node.js:154:7)
error Command failed with exit code 1.
```

*Any help would be appreciated!*

### Expected behaviour

No errors

### Code sample
N/A

### Screenshots (if applicable)
N/A

### What have you tried
As is shown above

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |N/A
| react-native          |latest
| react-native-paper    |material-next
| node                  |8.11.3
| npm or yarn           |0.27.5

**Comment by turtlegood** [comment]
I would appreciate it if you could send me or publish a compiled version of the document! Thank you very much!

**Comment by Trancever** [comment]
Hi @turtlegood .  This is the link you are looking for - https://3917-71323749-gh.circle-artifacts.com/0/docs/index.html

**Comment by turtlegood** [comment]
Wow thank you so much!
